### ISSUE TITLE
many thanks for your book

### ISSUE THREAD

**Issue by ousia** [crypto101/book#444] opened 2023-07-16 12:27 UTC
@lvh, many thanks for this introductory book to cryptography.

I have paged through and I cannot say I’m going to understand all the content it explains, but I’m looking forward to reading it.

BTW, I wonder  it might make sense to give an explanation of the [double ratchet algorithm](https://signal.org/docs/specifications/doubleratchet/).

At least, this will give some insight on what kind of encryption Signal offers.

Many thanks for your excellent work on tyour book again.

**Comment by lvh** [comment] 2023-07-16 17:26
Thanks! I think this ticket is almost a duplicate of #270 so I think we should track the work there :)

**Closed by lvh** 2023-07-16 17:26 UTC
