### ISSUE TITLE
nit: double quotes

### ISSUE THREAD

**Issue by trackpick** [crypto101/book#327] opened 2017-04-30 06:10 UTC
I didn't test this for this particular book, but when I wrote Latex in the past I used `` (two backticks) for an initial double quote and '' (two single quotes) for the final double quote. Currently, you're using " (single character double quote) for both, which doesn't end up looking right for the final double quote.

E.g. see http://www.maths.tcd.ie/~dwilkins/LaTeXPrimer/QuotDash.html

**Comment by EdOverflow** [comment] 2017-04-30 10:21
See https://github.com/crypto101/book/issues/294 for previous discussion.

**Comment by lvh** [comment] 2017-04-30 14:11
Thanks for submitting a ticket. The source file is org, not TeX, and that ought to be handling smart quotes. (This project intentionally does not maintain a LaTeX source, and if I could have my way, I'd be getting rid of more LaTeXisms since they're a pain in the neck for producing content for smaller screens.) Since @EdOverflow pointed out an older ticket, I'm closing this one as duplicate of that one.

**Closed by lvh** 2017-04-30 14:11 UTC
